### ISSUE TITLE
buttplug-tampermonkey-ui does not connect to Intiface Desktop

### ISSUE THREAD

**Issue by Baguettedood** [buttplugio/buttplug-tampermonkey#1]
When using buttplug-tampermonkey-ui and clicking the "Connect to Intiface Desktop" button, nothing happens.

Expected behavior: The UI would connect to Intiface Desktop

Looking at the code, it seems that `connect_browser_button` has an event listener for connecting in-browser, but `connect_intiface_button` does not have any event listener.

**Comment by qdot** [comment]
Partially fixed in #6, follow up for regular ws:// protocols filed in #7, calling this done.
